"""photos field

Revision ID: dfc310d92304
Revises: a8e055c5bee2
Create Date: 2019-02-07 20:25:45.325042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc310d92304'
down_revision = 'a8e055c5bee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'created')
    # ### end Alembic commands ###
